import type { Vehicle } from './types';

// Datos de ejemplo (se muestran cuando Supabase todavía no está configurado).
// Cuando cargues autos reales desde el panel /admin, estos dejan de usarse.
const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=70`;

export const demoVehicles: Vehicle[] = [
  {
    id: 'demo-1',
    slug: 'jeep-renegade-sport-2020',
    brand: 'Jeep',
    model: 'Renegade',
    version: 'Sport 1.8',
    year: 2020,
    price: 21900,
    currency: 'USD',
    km: 62000,
    transmission: 'automatica',
    fuel: 'nafta',
    body: 'suv',
    color: 'Gris',
    doors: 5,
    engine: '1.8 16v',
    status: 'disponible',
    featured: true,
    description:
      'Jeep Renegade Sport en excelente estado, único dueño, service oficial al día. Ideal ciudad y ruta.',
    features: ['Cámara de retroceso', 'Pantalla táctil', 'Control de estabilidad', 'Bluetooth', 'Llantas de aleación'],
    images: [img('photo-1533473359331-0135ef1b58bf')],
  },
  {
    id: 'demo-2',
    slug: 'ram-1500-laramie-2019',
    brand: 'RAM',
    model: '1500',
    version: 'Laramie',
    year: 2019,
    price: 38500,
    currency: 'USD',
    km: 78000,
    transmission: 'automatica',
    fuel: 'diesel',
    body: 'pickup',
    color: 'Negro',
    doors: 4,
    engine: '3.0 V6 EcoDiesel',
    status: 'disponible',
    featured: true,
    description:
      'Pick up RAM 1500 Laramie full, cuero, 4x4, impecable. Recibimos tu usado en parte de pago.',
    features: ['4x4', 'Asientos de cuero', 'Climatizador bizona', 'Sensores de estacionamiento', 'Tapizado premium'],
    images: [img('photo-1594502184342-2e12f877aa73')],
  },
  {
    id: 'demo-3',
    slug: 'ford-ranger-xlt-2021',
    brand: 'Ford',
    model: 'Ranger',
    version: 'XLT 3.2',
    year: 2021,
    price: 34900,
    currency: 'USD',
    km: 54000,
    transmission: 'automatica',
    fuel: 'diesel',
    body: 'pickup',
    color: 'Blanco',
    doors: 4,
    engine: '3.2 TDCi',
    status: 'reservado',
    featured: true,
    description: 'Ford Ranger XLT doble cabina, mantenimiento al día, cubiertas nuevas.',
    features: ['4x4', 'Control de descenso', 'Pantalla SYNC', 'Faros LED', 'Barra antivuelco'],
    images: [img('photo-1519641471654-76ce0107ad1b')],
  },
  {
    id: 'demo-4',
    slug: 'volkswagen-golf-comfortline-2018',
    brand: 'Volkswagen',
    model: 'Golf',
    version: 'Comfortline',
    year: 2018,
    price: 17500,
    currency: 'USD',
    km: 69000,
    transmission: 'automatica',
    fuel: 'nafta',
    body: 'hatchback',
    color: 'Plata',
    doors: 5,
    engine: '1.4 TSI',
    status: 'disponible',
    featured: false,
    description: 'Volkswagen Golf Comfortline, muy cuidado, ideal primer auto o ciudad.',
    features: ['Climatizador', 'Sensor de lluvia', 'Cámara trasera', 'Start/Stop'],
    images: [img('photo-1503376780353-7e6692767b70')],
  },
  {
    id: 'demo-5',
    slug: 'chevrolet-onix-lt-2022',
    brand: 'Chevrolet',
    model: 'Onix',
    version: 'LT',
    year: 2022,
    price: 15900,
    currency: 'USD',
    km: 38000,
    transmission: 'manual',
    fuel: 'nafta',
    body: 'sedan',
    color: 'Rojo',
    doors: 4,
    engine: '1.0 Turbo',
    status: 'disponible',
    featured: false,
    description: 'Chevrolet Onix Plus LT, bajo kilometraje, garantía vigente.',
    features: ['Pantalla MyLink', 'Android Auto', 'Airbags', 'Alarma'],
    images: [img('photo-1541443131876-44b03de101c5')],
  },
  {
    id: 'demo-6',
    slug: 'toyota-hilux-srv-2020',
    brand: 'Toyota',
    model: 'Hilux',
    version: 'SRV 2.8',
    year: 2020,
    price: 39900,
    currency: 'USD',
    km: 71000,
    transmission: 'automatica',
    fuel: 'diesel',
    body: 'pickup',
    color: 'Gris oscuro',
    doors: 4,
    engine: '2.8 TDI',
    status: 'disponible',
    featured: true,
    description: 'Toyota Hilux SRV 4x4, robusta y confiable, lista para el trabajo y la familia.',
    features: ['4x4', 'Cuero', 'Cámara 360', 'Control de tracción', 'Diferencial trasero'],
    images: [img('photo-1568605117036-5fe5e7bab0b7')],
  },
  {
    id: 'demo-7',
    slug: 'nissan-kicks-advance-2019',
    brand: 'Nissan',
    model: 'Kicks',
    version: 'Advance',
    year: 2019,
    price: 18900,
    currency: 'USD',
    km: 58000,
    transmission: 'automatica',
    fuel: 'nafta',
    body: 'suv',
    color: 'Blanco perla',
    doors: 5,
    engine: '1.6 CVT',
    status: 'disponible',
    featured: false,
    description: 'Nissan Kicks Advance, SUV urbana económica y espaciosa.',
    features: ['Cámara de retroceso', 'Pantalla táctil', 'Llantas de aleación', 'Control crucero'],
    images: [img('photo-1606664515524-ed2f786a0bd6')],
  },
  {
    id: 'demo-8',
    slug: 'fiat-cronos-drive-2021',
    brand: 'Fiat',
    model: 'Cronos',
    version: 'Drive 1.3',
    year: 2021,
    price: 14500,
    currency: 'USD',
    km: 41000,
    transmission: 'manual',
    fuel: 'nafta',
    body: 'sedan',
    color: 'Gris',
    doors: 4,
    engine: '1.3 Firefly',
    status: 'vendido',
    featured: false,
    description: 'Fiat Cronos Drive, económico y con bajo consumo. (Vendido — consultá por unidades similares).',
    features: ['Aire acondicionado', 'Dirección eléctrica', 'Bluetooth', 'Airbags'],
    images: [img('photo-1580273916550-e323be2ae537')],
  },
];
