import type { Vehicle } from './types';

// Catálogo real de JP Automóviles (fotos propias del local).
// La primera foto de cada vehículo es la de frente con el cartel de JP.
// Los precios son de referencia: se ajustan desde el panel /admin.
const pics = (slug: string, n = 6) =>
  Array.from({ length: n }, (_, i) => `/vehiculos/${slug}/${i + 1}.jpg`);

export const demoVehicles: Vehicle[] = [
  {
    id: 'jp-1',
    slug: 'ford-ranger-limited-2024',
    brand: 'Ford',
    model: 'Ranger',
    version: 'Limited 4WD',
    year: 2024,
    price: 62000,
    currency: 'USD',
    km: 0,
    transmission: 'automatica',
    fuel: 'diesel',
    body: 'pickup',
    color: 'Blanco',
    doors: 4,
    engine: '3.0 V6 Turbodiésel',
    status: 'disponible',
    featured: true,
    description:
      'Ford Ranger Limited 4WD 0 km, la pick up más completa de la gama. Motor V6 turbodiésel, tracción 4x4, caja automática y equipamiento full. Consultanos por financiación y permuta.',
    features: [
      'Tracción 4WD',
      'Caja automática',
      'Pantalla táctil SYNC',
      'Cámara de retroceso',
      'Control de estabilidad',
      'Faros LED',
      'Estribos laterales',
      'Barra deportiva',
    ],
    images: pics('ford-ranger-limited'),
  },
  {
    id: 'jp-2',
    slug: 'tesla-model-3-2024',
    brand: 'Tesla',
    model: 'Model 3',
    version: '100% eléctrico',
    year: 2024,
    price: 42000,
    currency: 'USD',
    km: 12000,
    transmission: 'automatica',
    fuel: 'electrico',
    body: 'sedan',
    color: 'Gris grafito',
    doors: 4,
    engine: 'Motor eléctrico',
    status: 'disponible',
    featured: true,
    description:
      'Tesla Model 3 100% eléctrico, en excelente estado. Tecnología de punta, gran autonomía y costo de mantenimiento mínimo. Una oportunidad única en Paysandú.',
    features: [
      'Motor 100% eléctrico',
      'Piloto automático',
      'Pantalla central 15"',
      'Techo panorámico',
      'Actualizaciones OTA',
      'Llantas deportivas',
    ],
    images: pics('tesla-model-3'),
  },
  {
    id: 'jp-3',
    slug: 'volkswagen-virtus-msi',
    brand: 'Volkswagen',
    model: 'Virtus',
    version: 'MSI',
    year: 2023,
    price: 23500,
    currency: 'USD',
    km: 35000,
    transmission: 'automatica',
    fuel: 'nafta',
    body: 'sedan',
    color: 'Gris',
    doors: 4,
    engine: '1.6 MSI',
    status: 'disponible',
    featured: true,
    description:
      'Volkswagen Virtus MSI en muy buen estado, ideal para ciudad y ruta. Amplio baúl, bajo consumo y service al día. Recibimos tu usado en parte de pago.',
    features: [
      'Caja automática',
      'Aire acondicionado',
      'Pantalla multimedia',
      'Cámara de retroceso',
      'Llantas de aleación',
      'Control de estabilidad',
    ],
    images: pics('vw-virtus'),
  },
  {
    id: 'jp-4',
    slug: 'audi-q2',
    brand: 'Audi',
    model: 'Q2',
    version: 'TFSI',
    year: 2019,
    price: 28900,
    currency: 'USD',
    km: 62000,
    transmission: 'automatica',
    fuel: 'nafta',
    body: 'suv',
    color: 'Blanco',
    doors: 5,
    engine: '1.4 TFSI',
    status: 'disponible',
    featured: false,
    description:
      'Audi Q2 blanca, SUV compacta premium con excelente terminación. Muy cuidada, ideal para quien busca calidad alemana en formato urbano.',
    features: [
      'Caja automática',
      'Climatizador',
      'Llantas de aleación',
      'Sensores de estacionamiento',
      'Volante multifunción',
      'Faros LED',
    ],
    images: pics('audi-q2'),
  },
  {
    id: 'jp-5',
    slug: 'mercedes-benz-clase-s',
    brand: 'Mercedes-Benz',
    model: 'Clase S',
    version: 'S 350',
    year: 2008,
    price: 27500,
    currency: 'USD',
    km: 145000,
    transmission: 'automatica',
    fuel: 'nafta',
    body: 'sedan',
    color: 'Gris plata',
    doors: 4,
    engine: '3.5 V6',
    status: 'disponible',
    featured: false,
    description:
      'Mercedes-Benz Clase S, el sedán de lujo por excelencia. Motor V6, interior en cuero y todo el confort de la marca. Un clásico impecablemente conservado.',
    features: [
      'Asientos de cuero',
      'Climatizador bizona',
      'Techo corredizo',
      'Suspensión neumática',
      'Llantas originales',
      'Sensores de estacionamiento',
    ],
    images: pics('mercedes-benz-clase-s'),
  },
  {
    id: 'jp-6',
    slug: 'ford-territory-hybrid',
    brand: 'Ford',
    model: 'Territory',
    version: 'Hybrid',
    year: 2025,
    price: 45900,
    currency: 'USD',
    km: 0,
    transmission: 'automatica',
    fuel: 'hibrido',
    body: 'suv',
    color: 'Negro',
    doors: 5,
    engine: 'Híbrido',
    status: 'disponible',
    featured: true,
    description:
      'Ford Territory Hybrid 0 km, la nueva SUV híbrida de Ford. Máxima tecnología, bajo consumo y un interior premium con pantallas de última generación.',
    features: [
      'Motorización híbrida',
      'Pantalla panorámica',
      'Interior premium',
      'Cámara 360',
      'Asistentes de conducción',
      'Llantas de aleación',
      'Techo panorámico',
    ],
    images: pics('ford-territory'),
  },
  {
    id: 'jp-7',
    slug: 'hyundai-hb20',
    brand: 'Hyundai',
    model: 'HB20',
    version: 'Comfort',
    year: 2023,
    price: 19900,
    currency: 'USD',
    km: 28000,
    transmission: 'manual',
    fuel: 'nafta',
    body: 'hatchback',
    color: 'Blanco',
    doors: 5,
    engine: '1.0',
    status: 'disponible',
    featured: false,
    description:
      'Hyundai HB20 blanco, muy económico y con bajo kilometraje. Ideal como primer auto o para uso diario en ciudad. Excelente estado general.',
    features: [
      'Aire acondicionado',
      'Dirección eléctrica',
      'Pantalla multimedia',
      'Bluetooth',
      'Llantas de aleación',
      'Airbags',
    ],
    images: pics('hyundai-hb20'),
  },
  {
    id: 'jp-8',
    slug: 'toyota-rav4',
    brand: 'Toyota',
    model: 'RAV4',
    version: 'XLE',
    year: 2018,
    price: 32900,
    currency: 'USD',
    km: 78000,
    transmission: 'automatica',
    fuel: 'nafta',
    body: 'suv',
    color: 'Bordó',
    doors: 5,
    engine: '2.0',
    status: 'disponible',
    featured: false,
    description:
      'Toyota RAV4 bordó, la SUV más confiable del mercado. Muy bien mantenida, con service al día y lista para entregar. Recibimos tu usado.',
    features: [
      'Caja automática',
      'Climatizador',
      'Cámara de retroceso',
      'Control crucero',
      'Llantas de aleación',
      'Faros antiniebla',
    ],
    images: pics('toyota-rav4'),
  },
  {
    id: 'jp-9',
    slug: 'leapmotor-b10',
    brand: 'Leapmotor',
    model: 'B10',
    version: '100% eléctrico',
    year: 2025,
    price: 38900,
    currency: 'USD',
    km: 0,
    transmission: 'automatica',
    fuel: 'electrico',
    body: 'suv',
    color: 'Blanco',
    doors: 5,
    engine: 'Motor eléctrico',
    status: 'disponible',
    featured: true,
    description:
      'Leapmotor B10 0 km, SUV 100% eléctrica con diseño moderno y equipamiento completo. Cero emisiones y mínimo costo de uso. Consultanos por disponibilidad.',
    features: [
      'Motor 100% eléctrico',
      'Pantalla central',
      'Cámara 360',
      'Asistentes de conducción',
      'Llantas de aleación',
      'Carga rápida',
    ],
    images: pics('leapmotor-b10'),
  },
  {
    id: 'jp-10',
    slug: 'jeep-renegade-longitude',
    brand: 'Jeep',
    model: 'Renegade',
    version: 'Longitude',
    year: 2023,
    price: 31900,
    currency: 'USD',
    km: 25000,
    transmission: 'automatica',
    fuel: 'nafta',
    body: 'suv',
    color: 'Gris',
    doors: 5,
    engine: '1.3 Turbo',
    status: 'disponible',
    featured: true,
    description:
      'Jeep Renegade Longitude gris, con el inconfundible diseño de la marca. Motor 1.3 turbo, caja automática y muy bajo kilometraje. Impecable.',
    features: [
      'Caja automática',
      'Faros LED',
      'Pantalla táctil',
      'Cámara de retroceso',
      'Barras de techo',
      'Control de estabilidad',
    ],
    images: pics('jeep-renegade'),
  },
];
